version: "3.9"
services:
  app:
    image: node:20-bullseye
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - ASTRO_TELEMETRY_DISABLED=1
      - NPM_CONFIG_FUND=false
      - NPM_CONFIG_AUDIT=false
    ports:
      - "4321:4321"
    command:
      - bash
      - -lc
      - |
        set -e
        npm install
        npm run dev -- --host 0.0.0.0 --port 4321
volumes:
  node_modules:
